#ifndef		_MYFUNC_H
#define		_MYFUNC_H

#include <stdint.h>
#include <stdio.h>

extern uint16_t Servo_ID;

extern void ServoStop(uint8_t ID);
extern void Key_Control(uint16_t Servo_ID);
//extern void Serial_GetAndSend(void);
extern void Joint_FeedBack(void);
extern void Servo_PosFeedBack(void);
extern void Screen_Control(void);
void Serial_FeedBack(void);
extern void SetServoMode(void);
extern void NormalGrasp(void);
extern void Grasptype_Control(void);
extern void Number1(void);
extern void Number2(void);
extern void Number3(void);
extern void Number4(void);
extern void Number5(void);
extern void Number6(void);
extern void Number7(void);
extern void Number8(void);
extern void Number9(void);
extern void Number10(void);
extern void Stop_Allservo(void);
extern void Kapandji_Test_1(void);
extern void Kapandji_Test_2(void);
extern void Kapandji_Test_3(void);
extern void Kapandji_Test_4(void);
extern void Kapandji_Test_5(void);
extern void Kapandji_Test_6(void);
extern void Kapandji_Test_7(void);
extern void Kapandji_Test_8(void);
extern void Kapandji_Test_9(void);
extern void Kapandji_Test_10(void);
extern void Kapandji_Test_11(void);
extern void Hand_grasp_1(void);
extern void Hand_grasp_2(void);
extern void Hand_grasp_3(void);
extern void Hand_grasp_4(void);
extern void Hand_grasp_5(void);
extern void Hand_grasp_6(void);
extern void Hand_grasp_7(void);
extern void Hand_grasp_8(void);
extern void Hand_grasp_9(void);
extern void Hand_grasp_10(void);
extern void Hand_grasp_11(void);
extern void Hand_grasp_12(void);
extern void Hand_grasp_13(void);
extern void Hand_grasp_14(void);
extern void Hand_grasp_15(void);
extern void Hand_grasp_16(void);
extern void Hand_grasp_17(void);
extern void Hand_grasp_18(void);
extern void Hand_grasp_19(void);
extern void Hand_grasp_20(void);
extern void Hand_grasp_21(void);
extern void Hand_grasp_22(void);
extern void Hand_grasp_23(void);
extern void Hand_grasp_24(void);
extern void Hand_grasp_25(void);
extern void Hand_grasp_26(void);
extern void Hand_grasp_27(void);
extern void Hand_grasp_28(void);
extern void Hand_grasp_29(void);
extern void Hand_grasp_30(void);
extern void Hand_grasp_31(void);
extern void Hand_grasp_32(void);
extern void Hand_grasp_33(void);
extern void Hand_grasp_34(void);
extern void Hand_grasp_35(void);
extern void Hand_grasp_36(void);
extern void Hand_grasp_37(void);
extern void Hand_grasp_38(void);
extern void Hand_grasp_39(void);
extern void Hand_grasp_40(void);
extern void Hand_grasp_41(void);
extern void Hand_grasp_42(void);
extern void Hand_grasp_43(void);
extern void Hand_grasp_44(void);
extern void Hand_grasp_45(void);
extern void Hand_grasp_46(void);
extern void Hand_grasp_47(void);
extern void Hand_grasp_48(void);
extern void Hand_grasp_49(void);
extern void Hand_grasp_50(void);
extern void Hand_grasp_51(void);
extern void Hand_grasp_52(void);
extern void Stable_grasp1(void);
extern void Stable_grasp2(void);
extern void Stable_grasp3(void);
extern void Stable_grasp4(void);
extern void Stable_grasp5(void);
extern void Stable_grasp6(void);
extern void Stable_grasp7(void);
extern void Stable_grasp8(void);
extern void Stable_grasp9(void);
extern void Stable_grasp10(void);
extern void Stable_grasp11(void);
extern void Stable_grasp12(void);
extern void Stable_grasp13(void);
extern void Stable_grasp14(void);
extern void Motor11_Reciprocate_Once(void);
extern void Motor11_StepPause_Once(void);
extern void Motor24_Reach500Pause_Once(void);
extern void Motor14_Reset_1600(void);
#endif
